version: "3"
services:
       speedtester:
           container_name: speedtester       
           restart: always
           build: .
           ports:
             - "8080:8080"
           external_links:
             - mongo
       mongo:
             container_name: mongo
             image: arm64v8/mongo:4.4.12-focal
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'