version: "3"
services:
       speedtester:
           container_name: speedtester       
           restart: always
           build: .
           ports:
             - "8000:8000"
           external_links:
             - mongo
       mongo:
          container_name: mongo
          restart: always
          image: ${MONGO_IMAGE_NAME}
          volumes:
            - ./data:/data/db
          ports:
            - '27017:27017'