version: "3"
services:
  speedtester:
    container_name: speedtester    
    environment:          
      - PORT=${APP_PORT}      
    restart: always
    build: .
    ports:
      - "${HTTP_PORT}:${APP_PORT}"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: ${MONGO_IMAGE_NAME}
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'