version: "3"
services:
  speedtester:
    container_name: dynamikarray/speedtester:latest
    restart: always
    build: .
    ports:
      - "${HTTP_PORT}:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: ${MONGO_IMAGE_NAME}
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'